apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/khbeck/k8-eks-argocd-terraform.git
      revision: HEAD
      directories:
      - path: sample-apps/git-dir-generators/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/khbeck/k8-eks-argocd-terraform.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
